"use client";

/**
 * RFPClient — Interactive RFP/RFI Answer Engine.
 *
 * Steps:
 *   1. Select AI systems (multi-select, max 5)
 *   2. Enter RFP/RFI questions (one per line or individually, max 20)
 *   3. Optional company context
 *   4. Generate — progress indicator per question
 *   5. Results — Q&A cards with Copy All and Export
 */

import { useState, useEffect, useMemo } from "react";
import { useT } from "@/lib/locale-context";
import type { SubscriptionTier } from "@/lib/tier-access";

// ─── Types ────────────────────────────────────────────────

interface SystemOption {
  slug: string;
  vendor: string;
  name: string;
}

interface RFPAnswer {
  question: string;
  answer: string;
  systemsReferenced: string[];
}

interface Props {
  tier: SubscriptionTier;
  locale: string;
}

// ─── Component ────────────────────────────────────────────

export function RFPClient({ tier, locale }: Props) {
  const t = useT();
  const hasAccess = tier === "enterprise";

  // Systems list
  const [systems, setSystems] = useState<SystemOption[]>([]);
  const [systemsLoading, setSystemsLoading] = useState(true);

  // Form state
  const [selectedSlugs, setSelectedSlugs] = useState<string[]>([]);
  const [systemSearch, setSystemSearch] = useState("");
  const [questionsText, setQuestionsText] = useState("");
  const [companyContext, setCompanyContext] = useState("");

  // Generation state
  const [loading, setLoading] = useState(false);
  const [progressIndex, setProgressIndex] = useState(0);
  const [error, setError] = useState("");
  const [answers, setAnswers] = useState<RFPAnswer[]>([]);
  const [copied, setCopied] = useState(false);

  // Fetch systems on mount
  useEffect(() => {
    fetch("/api/v1/systems")
      .then((res) => res.json())
      .then((data) => {
        const list = (data.systems || data || []).map((s: SystemOption) => ({
          slug: s.slug,
          vendor: s.vendor,
          name: s.name,
        }));
        setSystems(list);
      })
      .catch(() => setSystems([]))
      .finally(() => setSystemsLoading(false));
  }, []);

  // Parse questions from textarea
  const questions = useMemo(() => {
    return questionsText
      .split("\n")
      .map((q) => q.trim())
      .filter((q) => q.length > 0);
  }, [questionsText]);

  // Filtered systems for search
  const filteredSystems = useMemo(() => {
    if (!systemSearch.trim()) return systems;
    const q = systemSearch.toLowerCase();
    return systems.filter(
      (s) =>
        s.name.toLowerCase().includes(q) ||
        s.vendor.toLowerCase().includes(q),
    );
  }, [systems, systemSearch]);

  // ─── Toggle System Selection ─────────────────────────────

  function toggleSystem(slug: string) {
    setSelectedSlugs((prev) => {
      if (prev.includes(slug)) return prev.filter((s) => s !== slug);
      if (prev.length >= 5) return prev;
      return [...prev, slug];
    });
  }

  // ─── Generate Answers ────────────────────────────────────

  async function handleGenerate() {
    if (selectedSlugs.length === 0) {
      setError("Please select at least one AI system.");
      return;
    }
    if (questions.length === 0) {
      setError("Please enter at least one question.");
      return;
    }
    if (questions.length > 20) {
      setError("Maximum 20 questions allowed. Please reduce your list.");
      return;
    }

    setLoading(true);
    setError("");
    setAnswers([]);
    setProgressIndex(0);

    // Simulate progress (server processes sequentially)
    const progressInterval = setInterval(() => {
      setProgressIndex((prev) => Math.min(prev + 1, questions.length));
    }, 3000);

    try {
      const res = await fetch("/api/rfp", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          questions,
          systemSlugs: selectedSlugs,
          companyContext: companyContext.trim() || undefined,
        }),
      });

      const data = await res.json();

      if (!res.ok) {
        setError(data.error || "Failed to generate answers.");
        return;
      }

      setAnswers(data.answers);
      setProgressIndex(questions.length);
    } catch {
      setError("Network error. Please check your connection and try again.");
    } finally {
      clearInterval(progressInterval);
      setLoading(false);
    }
  }

  // ─── Copy All ─────────────────────────────────────────────

  async function handleCopyAll() {
    const selectedNames = selectedSlugs
      .map((slug) => {
        const sys = systems.find((s) => s.slug === slug);
        return sys ? `${sys.vendor} ${sys.name}` : slug;
      })
      .join(", ");

    const text =
      `RFP/RFI RESPONSE DOCUMENT\nGenerated by AI Compass EU\nDate: ${new Date().toLocaleDateString(locale, { day: "numeric", month: "long", year: "numeric" })}\nSystems: ${selectedNames}\n\n` +
      answers
        .map((a, i) => `---\n\nQ${i + 1}: ${a.question}\n\n${a.answer}`)
        .join("\n\n");

    try {
      await navigator.clipboard.writeText(text);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      const textarea = document.createElement("textarea");
      textarea.value = text;
      document.body.appendChild(textarea);
      textarea.select();
      document.execCommand("copy");
      document.body.removeChild(textarea);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  }

  // ─── Export as Text File ──────────────────────────────────

  function handleExport() {
    const selectedNames = selectedSlugs
      .map((slug) => {
        const sys = systems.find((s) => s.slug === slug);
        return sys ? `${sys.vendor} ${sys.name}` : slug;
      })
      .join(", ");

    const text =
      `RFP/RFI RESPONSE DOCUMENT\nGenerated by AI Compass EU\nDate: ${new Date().toLocaleDateString(locale, { day: "numeric", month: "long", year: "numeric" })}\nSystems: ${selectedNames}\n\n` +
      answers
        .map((a, i) => `${"=".repeat(60)}\n\nQ${i + 1}: ${a.question}\n\n${a.answer}`)
        .join("\n\n");

    const blob = new Blob([text], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `rfp-response-${new Date().toISOString().slice(0, 10)}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }

  // ─── Free/Pro Tier Gate ─────────────────────────────────

  if (!hasAccess) {
    return (
      <div className="relative">
        {/* Blurred preview */}
        <div className="pointer-events-none select-none blur-sm opacity-50">
          <div className="grid gap-6 lg:grid-cols-3">
            <div className="rounded-xl border border-gray-200 bg-white p-6 shadow-sm">
              <h3 className="text-sm font-semibold text-gray-500 uppercase tracking-wider mb-4">
                1. Select AI Systems
              </h3>
              <div className="space-y-2">
                <div className="h-10 bg-gray-100 rounded-lg" />
                <div className="h-8 bg-gray-100 rounded-lg w-3/4" />
                <div className="h-8 bg-gray-100 rounded-lg w-5/6" />
              </div>
            </div>
            <div className="rounded-xl border border-gray-200 bg-white p-6 shadow-sm">
              <h3 className="text-sm font-semibold text-gray-500 uppercase tracking-wider mb-4">
                2. Paste RFP Questions
              </h3>
              <div className="space-y-2">
                <div className="h-32 bg-gray-100 rounded-lg" />
                <div className="h-4 bg-gray-100 rounded w-1/3" />
              </div>
            </div>
            <div className="rounded-xl border border-gray-200 bg-white p-6 shadow-sm">
              <h3 className="text-sm font-semibold text-gray-500 uppercase tracking-wider mb-4">
                3. Company Context
              </h3>
              <div className="h-20 bg-gray-100 rounded-lg" />
            </div>
          </div>
          <div className="mt-6 space-y-4">
            {[1, 2, 3].map((n) => (
              <div key={n} className="rounded-xl border border-gray-200 bg-white p-6 shadow-sm">
                <div className="h-5 bg-gray-100 rounded w-2/3 mb-3" />
                <div className="space-y-2">
                  <div className="h-4 bg-gray-100 rounded w-full" />
                  <div className="h-4 bg-gray-100 rounded w-5/6" />
                  <div className="h-4 bg-gray-100 rounded w-4/6" />
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Upgrade CTA overlay */}
        <div className="absolute inset-0 flex items-center justify-center">
          <div className="rounded-2xl bg-white/95 backdrop-blur-sm border border-[#003399]/20 shadow-xl px-8 py-10 text-center max-w-lg mx-4">
            <div className="mx-auto mb-4 flex h-14 w-14 items-center justify-center rounded-full bg-[#003399]/10">
              <svg className="h-7 w-7 text-[#003399]" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.5}>
                <path strokeLinecap="round" strokeLinejoin="round" d="M16.5 10.5V6.75a4.5 4.5 0 10-9 0v3.75m-.75 11.25h10.5a2.25 2.25 0 002.25-2.25v-6.75a2.25 2.25 0 00-2.25-2.25H6.75a2.25 2.25 0 00-2.25 2.25v6.75a2.25 2.25 0 002.25 2.25z" />
              </svg>
            </div>
            <h2 className="text-xl font-bold text-[#0d1b3e] font-serif">
              Unlock the RFP/RFI Answer Engine
            </h2>
            <p className="mt-3 text-gray-600 text-sm leading-relaxed">
              Generate professional draft answers to RFP and RFI questions,
              grounded in real compliance data, certifications, and EU regulatory intelligence.
              Available exclusively on the Enterprise plan.
            </p>
            <a
              href={`/${locale}/pricing`}
              className="mt-6 inline-flex items-center gap-2 rounded-lg bg-[#003399] px-6 py-3 text-sm font-semibold text-white shadow-sm hover:bg-[#002266] transition-colors"
            >
              Upgrade to Enterprise
              <svg className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                <path strokeLinecap="round" strokeLinejoin="round" d="M13.5 4.5L21 12m0 0l-7.5 7.5M21 12H3" />
              </svg>
            </a>
            <p className="mt-3 text-xs text-gray-400">
              Contact us for Enterprise pricing
            </p>
          </div>
        </div>
      </div>
    );
  }

  // ─── Results View ───────────────────────────────────────

  if (answers.length > 0) {
    return (
      <div>
        {/* Action bar */}
        <div className="mb-6 flex flex-wrap items-center justify-between gap-3 print:hidden">
          <button
            onClick={() => setAnswers([])}
            className="inline-flex items-center gap-2 rounded-lg border border-gray-300 bg-white px-4 py-2 text-sm font-medium text-gray-700 hover:bg-gray-50 transition-colors"
          >
            <svg className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M10.5 19.5L3 12m0 0l7.5-7.5M3 12h18" />
            </svg>
            New RFP Session
          </button>

          <div className="flex items-center gap-2">
            <button
              onClick={handleCopyAll}
              className="inline-flex items-center gap-2 rounded-lg border border-gray-300 bg-white px-4 py-2 text-sm font-medium text-gray-700 hover:bg-gray-50 transition-colors"
            >
              <svg className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                <path strokeLinecap="round" strokeLinejoin="round" d="M15.666 3.888A2.25 2.25 0 0013.5 2.25h-3c-1.03 0-1.9.693-2.166 1.638m7.332 0c.055.194.084.4.084.612v0a.75.75 0 01-.75.75H9.75a.75.75 0 01-.75-.75v0c0-.212.03-.418.084-.612m7.332 0c.646.049 1.288.11 1.927.184 1.1.128 1.907 1.077 1.907 2.185V19.5a2.25 2.25 0 01-2.25 2.25H6.75A2.25 2.25 0 014.5 19.5V6.257c0-1.108.806-2.057 1.907-2.185a48.208 48.208 0 011.927-.184" />
              </svg>
              {copied ? "Copied!" : "Copy All"}
            </button>
            <button
              onClick={handleExport}
              className="inline-flex items-center gap-2 rounded-lg bg-[#003399] px-4 py-2 text-sm font-semibold text-white shadow-sm hover:bg-[#002266] transition-colors"
            >
              <svg className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                <path strokeLinecap="round" strokeLinejoin="round" d="M3 16.5v2.25A2.25 2.25 0 005.25 21h13.5A2.25 2.25 0 0021 18.75V16.5M16.5 12L12 16.5m0 0L7.5 12m4.5 4.5V3" />
              </svg>
              Export
            </button>
          </div>
        </div>

        {/* Header */}
        <div className="mb-8 rounded-xl border border-[#003399]/20 bg-gradient-to-r from-[#003399]/5 to-transparent p-6">
          <p className="text-xs font-medium uppercase tracking-wider text-[#003399] mb-1">
            AI Compass EU — RFP/RFI Response
          </p>
          <h2 className="text-2xl font-bold text-[#0d1b3e] font-serif">
            {answers.length} Question{answers.length !== 1 ? "s" : ""} Answered
          </h2>
          <p className="mt-1 text-sm text-gray-500">
            Generated {new Date().toLocaleDateString(locale, { day: "numeric", month: "long", year: "numeric" })}
            {" "}&middot;{" "}
            Systems: {answers[0]?.systemsReferenced.join(", ")}
          </p>
        </div>

        {/* Q&A Cards */}
        <div className="space-y-6">
          {answers.map((a, i) => (
            <div
              key={i}
              className="rounded-xl border border-gray-200 bg-white shadow-sm overflow-hidden"
            >
              {/* Question */}
              <div className="border-b border-gray-100 bg-gray-50 px-6 py-4">
                <div className="flex items-start gap-3">
                  <span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-[#003399] text-xs font-bold text-white mt-0.5">
                    Q{i + 1}
                  </span>
                  <p className="text-sm font-semibold text-[#0d1b3e] leading-relaxed">
                    {a.question}
                  </p>
                </div>
              </div>
              {/* Answer */}
              <div className="px-6 py-5">
                <div
                  className="prose prose-sm max-w-none text-gray-700 prose-headings:text-[#0d1b3e] prose-headings:font-serif prose-strong:text-[#0d1b3e] prose-a:text-[#003399]"
                  dangerouslySetInnerHTML={{ __html: markdownToHtml(a.answer) }}
                />
              </div>
            </div>
          ))}
        </div>

        {/* Disclaimer */}
        <div className="mt-8 rounded-lg bg-amber-50 border border-amber-200 p-4 text-xs text-amber-800">
          <p className="font-semibold mb-1">Disclaimer</p>
          <p>
            These draft answers are generated by AI based on AI Compass EU assessment data.
            All responses should be reviewed and validated by your procurement team before
            inclusion in any formal RFP/RFI submission. This does not constitute legal or procurement advice.
          </p>
        </div>
      </div>
    );
  }

  // ─── Form View ──────────────────────────────────────────

  return (
    <div>
      <div className="grid gap-6 lg:grid-cols-3">
        {/* Step 1: Select Systems */}
        <div className="rounded-xl border border-gray-200 bg-white p-6 shadow-sm">
          <h3 className="text-sm font-semibold text-[#003399] uppercase tracking-wider mb-4 flex items-center gap-2">
            <span className="flex h-6 w-6 items-center justify-center rounded-full bg-[#003399] text-xs font-bold text-white">
              1
            </span>
            Select AI Systems
            <span className="ml-auto text-xs font-normal text-gray-400">
              {selectedSlugs.length}/5
            </span>
          </h3>

          {/* Search */}
          <input
            type="text"
            value={systemSearch}
            onChange={(e) => setSystemSearch(e.target.value)}
            placeholder="Search systems..."
            className="w-full rounded-lg border border-gray-300 px-3 py-2 text-sm text-gray-900 placeholder-gray-400 focus:border-[#003399] focus:ring-1 focus:ring-[#003399] transition-colors mb-3"
          />

          {/* System checkboxes */}
          <div className="max-h-64 overflow-y-auto space-y-1 pr-1">
            {systemsLoading ? (
              <div className="py-4 text-center text-sm text-gray-400">Loading systems...</div>
            ) : filteredSystems.length === 0 ? (
              <div className="py-4 text-center text-sm text-gray-400">No systems found</div>
            ) : (
              filteredSystems.map((s) => {
                const isSelected = selectedSlugs.includes(s.slug);
                const isDisabled = !isSelected && selectedSlugs.length >= 5;
                return (
                  <label
                    key={s.slug}
                    className={`flex items-center gap-2.5 rounded-lg px-2.5 py-2 text-sm cursor-pointer transition-colors ${
                      isSelected
                        ? "bg-[#003399]/5 border border-[#003399]/20"
                        : isDisabled
                          ? "opacity-40 cursor-not-allowed"
                          : "hover:bg-gray-50 border border-transparent"
                    }`}
                  >
                    <input
                      type="checkbox"
                      checked={isSelected}
                      disabled={isDisabled}
                      onChange={() => toggleSystem(s.slug)}
                      className="h-4 w-4 rounded border-gray-300 text-[#003399] focus:ring-[#003399]"
                    />
                    <span className="truncate">
                      <span className="font-medium text-gray-900">{s.vendor}</span>
                      <span className="text-gray-400 mx-1">-</span>
                      <span className="text-gray-600">{s.name}</span>
                    </span>
                  </label>
                );
              })
            )}
          </div>

          {selectedSlugs.length > 0 && (
            <div className="mt-3 flex flex-wrap gap-1.5">
              {selectedSlugs.map((slug) => {
                const sys = systems.find((s) => s.slug === slug);
                return (
                  <span
                    key={slug}
                    className="inline-flex items-center gap-1 rounded-full bg-[#003399]/10 px-2.5 py-1 text-xs font-medium text-[#003399]"
                  >
                    {sys ? sys.name : slug}
                    <button
                      onClick={() => toggleSystem(slug)}
                      className="ml-0.5 hover:text-red-600 transition-colors"
                    >
                      <svg className="h-3 w-3" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                        <path strokeLinecap="round" strokeLinejoin="round" d="M6 18L18 6M6 6l12 12" />
                      </svg>
                    </button>
                  </span>
                );
              })}
            </div>
          )}
        </div>

        {/* Step 2: Enter Questions */}
        <div className="rounded-xl border border-gray-200 bg-white p-6 shadow-sm">
          <h3 className="text-sm font-semibold text-[#003399] uppercase tracking-wider mb-4 flex items-center gap-2">
            <span className="flex h-6 w-6 items-center justify-center rounded-full bg-[#003399] text-xs font-bold text-white">
              2
            </span>
            Paste RFP/RFI Questions
            <span className="ml-auto text-xs font-normal text-gray-400">
              {questions.length}/20
            </span>
          </h3>

          <textarea
            value={questionsText}
            onChange={(e) => setQuestionsText(e.target.value)}
            placeholder={"Paste your RFP/RFI questions here, one per line.\n\nExample:\nDescribe your AI system's compliance with the EU AI Act.\nWhat data residency options are available within the EU?\nHow does the system handle personal data under GDPR?\nWhat certifications does the vendor hold (ISO 27001, SOC 2, etc.)?"}
            rows={10}
            className="w-full rounded-lg border border-gray-300 px-3 py-2.5 text-sm text-gray-900 placeholder-gray-400 focus:border-[#003399] focus:ring-1 focus:ring-[#003399] transition-colors resize-none"
          />

          {questions.length > 0 && (
            <p className="mt-2 text-xs text-gray-500">
              {questions.length} question{questions.length !== 1 ? "s" : ""} detected
              {questions.length > 20 && (
                <span className="text-red-600 font-medium"> (max 20 — please reduce)</span>
              )}
            </p>
          )}
        </div>

        {/* Step 3: Company Context (Optional) */}
        <div className="rounded-xl border border-gray-200 bg-white p-6 shadow-sm">
          <h3 className="text-sm font-semibold text-[#003399] uppercase tracking-wider mb-4 flex items-center gap-2">
            <span className="flex h-6 w-6 items-center justify-center rounded-full bg-[#003399]/20 text-xs font-bold text-[#003399]">
              3
            </span>
            Company Context
            <span className="ml-auto text-xs font-normal text-gray-400">Optional</span>
          </h3>

          <textarea
            value={companyContext}
            onChange={(e) => setCompanyContext(e.target.value)}
            placeholder={"Provide context about your organisation to personalise answers.\n\nExample:\nWe are a 500-person financial services company based in Frankfurt. We process sensitive client data subject to DORA and BaFin regulations. We need EU-hosted solutions with SOC 2 certification."}
            rows={6}
            className="w-full rounded-lg border border-gray-300 px-3 py-2.5 text-sm text-gray-900 placeholder-gray-400 focus:border-[#003399] focus:ring-1 focus:ring-[#003399] transition-colors resize-none"
          />

          <p className="mt-2 text-xs text-gray-500">
            This helps tailor answers to your specific regulatory context and requirements.
          </p>
        </div>
      </div>

      {/* Error */}
      {error && (
        <div className="mt-4 rounded-lg bg-red-50 border border-red-200 px-4 py-3 text-sm text-red-700">
          {error}
        </div>
      )}

      {/* Generate Button */}
      <div className="mt-6 flex justify-center">
        <button
          onClick={handleGenerate}
          disabled={loading || selectedSlugs.length === 0 || questions.length === 0}
          className="inline-flex items-center gap-2 rounded-lg bg-[#003399] px-8 py-3 text-base font-semibold text-white shadow-md hover:bg-[#002266] disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
        >
          {loading ? (
            <>
              <svg className="h-5 w-5 animate-spin" viewBox="0 0 24 24" fill="none">
                <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
              </svg>
              Generating Answers...
            </>
          ) : (
            <>
              <svg className="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                <path strokeLinecap="round" strokeLinejoin="round" d="M9.813 15.904L9 18.75l-.813-2.846a4.5 4.5 0 00-3.09-3.09L2.25 12l2.846-.813a4.5 4.5 0 003.09-3.09L9 5.25l.813 2.846a4.5 4.5 0 003.09 3.09L15.75 12l-2.846.813a4.5 4.5 0 00-3.09 3.09zM18.259 8.715L18 9.75l-.259-1.035a3.375 3.375 0 00-2.455-2.456L14.25 6l1.036-.259a3.375 3.375 0 002.455-2.456L18 2.25l.259 1.035a3.375 3.375 0 002.455 2.456L21.75 6l-1.036.259a3.375 3.375 0 00-2.455 2.456z" />
              </svg>
              Generate {questions.length > 0 ? `${questions.length} Answer${questions.length !== 1 ? "s" : ""}` : "Answers"}
            </>
          )}
        </button>
      </div>

      {/* Loading progress */}
      {loading && (
        <div className="mt-6 rounded-xl border border-[#003399]/20 bg-[#003399]/5 p-6">
          <div className="flex items-center gap-3 text-[#003399] mb-3">
            <svg className="h-6 w-6 animate-spin" viewBox="0 0 24 24" fill="none">
              <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
              <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
            </svg>
            <span className="font-medium">
              Answering question {Math.min(progressIndex + 1, questions.length)} of {questions.length}...
            </span>
          </div>
          {/* Progress bar */}
          <div className="h-2 w-full rounded-full bg-[#003399]/10 overflow-hidden">
            <div
              className="h-full rounded-full bg-[#003399] transition-all duration-500"
              style={{ width: `${(progressIndex / questions.length) * 100}%` }}
            />
          </div>
          <p className="mt-2 text-xs text-[#003399]/70">
            Each question is processed sequentially for accuracy. This may take a few minutes.
          </p>
        </div>
      )}
    </div>
  );
}

// ─── Simple Markdown to HTML Converter ─────────────────────

function markdownToHtml(md: string): string {
  return md
    .replace(/^#### (.+)$/gm, '<h4 class="text-sm font-semibold mt-4 mb-1">$1</h4>')
    .replace(/^### (.+)$/gm, '<h3 class="text-base font-semibold mt-4 mb-2">$1</h3>')
    .replace(/^## (.+)$/gm, '<h2 class="text-lg font-semibold mt-4 mb-2">$1</h2>')
    .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
    .replace(/\*(.+?)\*/g, "<em>$1</em>")
    .replace(/^- (.+)$/gm, '<li class="ml-4 list-disc">$1</li>')
    .replace(/^\d+\. (.+)$/gm, '<li class="ml-4 list-decimal">$1</li>')
    .replace(/\n\n/g, "</p><p>")
    .replace(/^(.+)/, "<p>$1")
    .replace(/(.+)$/, "$1</p>");
}
