/**
 * Report content loader — Locale-aware access to research reports.
 *
 * Source of truth: src/data/reports/en.json (English).
 * Auto-translated locales live alongside as {locale}.json (regenerated by
 * `npm run i18n:translate`). Translated reports carry `autoTranslated: true`
 * so the UI can surface a "pending human review" disclaimer.
 *
 * Tier gating: first FREE_SECTIONS_COUNT sections are free; rest require Pro.
 */

import enReports from "./reports/en.json";
import { type Locale } from "@/lib/i18n";

export interface ReportSection {
  id: string;
  heading: string;
  content: string;
}

export interface ReportContent {
  slug: string;
  title: string;
  subtitle: string;
  category: string;
  date: string;
  readingTime: string;
  author: string;
  sections: ReportSection[];
  autoTranslated?: boolean;
}

export const REPORT_DISCLAIMER =
  "This report was generated with AI assistance and reviewed by domain experts. Data reflects publicly available information as of April 2026.";

export const AUTO_TRANSLATED_DISCLAIMER =
  "This translation was generated automatically and is pending human review. Refer to the English original for authoritative wording.";

export const FREE_SECTIONS_COUNT = 2;

const EN = enReports as ReportContent[];

// Lazy cache of locale-specific reports loaded via dynamic import
const localeCache = new Map<string, ReportContent[]>([["en", EN]]);

async function loadForLocale(locale: Locale): Promise<ReportContent[]> {
  if (localeCache.has(locale)) return localeCache.get(locale)!;
  try {
    const mod = await import(`./reports/${locale}.json`);
    const data = (mod.default ?? mod) as ReportContent[];
    localeCache.set(locale, data);
    return data;
  } catch {
    // Fallback to English if locale file is missing (should be blocked by i18n:check)
    localeCache.set(locale, EN);
    return EN;
  }
}

/**
 * Get a report by slug in the given locale. Falls back to English if the
 * localized version isn't available.
 */
export async function getReportBySlug(
  slug: string,
  locale: Locale = "en"
): Promise<ReportContent | undefined> {
  const reports = await loadForLocale(locale);
  return reports.find((r) => r.slug === slug);
}

/**
 * Get all report slugs from the English source (slugs are stable across locales).
 */
export function getAllReportSlugs(): string[] {
  return EN.map((r) => r.slug);
}

/** Get all reports for a locale (used by the reports index page). */
export async function getAllReports(locale: Locale = "en"): Promise<ReportContent[]> {
  return loadForLocale(locale);
}
