/**
 * Regulatory Framework Enrichment — Batch 3: Data Act, DSA, DMA
 *
 * Adds three new frameworks critical for enterprise AI procurement:
 * - EU Data Act: data sharing, portability, and cloud switching rights
 * - Digital Services Act (DSA): platform obligations and algorithmic transparency
 * - Digital Markets Act (DMA): gatekeeper obligations and interoperability
 *
 * Run with: npx tsx src/data/seed-frameworks-batch3.ts
 * Safe to run multiple times (uses upsert on slug).
 */

import dotenv from "dotenv";
dotenv.config({ path: ".env.local" });

import { PrismaClient } from "../generated/prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL! });
const prisma = new PrismaClient({ adapter });

// ─── New Framework Definitions ─────────────────────────────

const frameworks = [
  // ── EU Data Act ───────────────────────────────────────────
  {
    slug: "data-act",
    name: "EU Data Act",
    description:
      "The EU Data Act (Regulation 2023/2854) establishes harmonized rules on fair access to and use of data generated by connected products and related services. It introduces cloud switching rights, data portability obligations, and safeguards against unfair contract terms. Directly impacts AI tool procurement by giving enterprises the right to switch cloud/AI providers and access their data.",
    content: `## EU Data Act — Data Access, Portability & Cloud Switching

### Overview

The EU Data Act (Regulation (EU) 2023/2854) was adopted on 13 December 2023 and applies from **12 September 2025**. It is the first horizontal EU legislation establishing rules on who can use and access data generated by connected products (IoT devices, industrial machines, connected vehicles, smart appliances) and related services.

**Key purpose**: Break data silos, enable fair data access, prevent vendor lock-in, and create a level playing field for data-driven services including AI.

### Why It Matters for AI Procurement

The Data Act directly impacts enterprise AI tool selection in four ways:
1. **Cloud switching rights**: You can switch AI/cloud providers without excessive penalties or data loss
2. **Data portability**: Your data must be exportable in standard, machine-readable formats
3. **Fair contract terms**: Protects SMEs against unfair data access clauses in AI vendor contracts
4. **Public sector data access**: Government can request private sector data in emergencies (e.g., pandemic response AI)

### Key Provisions

**Chapter II — Business-to-Consumer & Business-to-Business Data Sharing (Articles 3-12)**

Users of connected products have the right to access data generated by those products. Data holders must make data available promptly, continuously, and in a commonly used machine-readable format.

For AI procurement: If you deploy IoT/connected devices with AI analytics, the data generated belongs to you (the user), not the device manufacturer or AI service provider. You can share this data with third-party AI providers of your choice.

**Chapter III — Unfair Contract Terms (Articles 13-14)**

Contract terms relating to data access and use are unfair and not binding if they:
- Grossly deviate from good commercial practice
- Exclude liability for intentional acts or gross negligence
- Give one party unilateral right to interpret or change contract terms

For AI procurement: Standard form AI vendor contracts cannot include unfair data access restrictions. SMEs are specifically protected. Review your AI vendor agreements for clauses that restrict your data access or portability rights.

**Chapter IV — Data Sharing with Public Sector (Articles 14-22)**

Public sector bodies can request data from private companies in cases of public emergencies (natural disasters, pandemics) or to fulfill statutory tasks where data is not otherwise available. Compensation limited to marginal cost of making data available.

**Chapter VI — Cloud Switching and Interoperability (Articles 23-31)**

This is the most impactful chapter for AI procurement:

- **Switching charges reduced to zero**: From 12 January 2027, cloud and AI service providers cannot charge switching fees. Transition period: charges gradually reduce from Sept 2025.
- **Maximum switching period**: 30 calendar days (can be extended to 60 with justification)
- **Functional equivalence**: After switching, the receiving provider must achieve substantially similar results if using the same data structures, formats, and standards
- **Data portability**: All customer data must be exportable in standard formats
- **No vendor lock-in**: Providers cannot impose contractual, commercial, technical, or organizational barriers to switching
- **Open interfaces**: Cloud/AI providers must publish technical specifications for data portability

**Chapter VII — International Data Access Safeguards (Articles 32-34)**

Protection against unlawful third-country government access to non-personal data held in the EU. Cloud/AI providers must take reasonable measures to prevent non-EU government access that conflicts with EU law.

For AI procurement: Reinforces data sovereignty. Cloud/AI providers cannot comply with non-EU government data requests that violate EU law (e.g., US CLOUD Act demands for EU-stored data).

### Enforcement Timeline

- **13 December 2023**: Data Act adopted
- **11 January 2024**: Entered into force
- **12 September 2025**: **Applies** (general application date)
- **12 September 2026**: Chapter III (unfair terms) applies to contracts concluded before 12 Sept 2025
- **12 January 2027**: Switching charges reduced to zero
- **12 September 2027**: Chapter II obligations for connected products placed on market before 12 Sept 2025

### Penalties

Member states define penalties. The Data Act requires they be **effective, proportionate, and dissuasive**. No specific maximum amount set at EU level — defined by national implementing legislation.

### Data Act ↔ GDPR Relationship

The Data Act does NOT replace GDPR. Where data includes personal data:
- GDPR requirements apply in full (legal basis, data minimization, rights of data subjects)
- Data Act adds additional rights (data access, portability for non-personal data)
- Data Act explicitly prohibits using data obtained under its provisions to profile individuals or undermine data subjects' GDPR rights

### Data Act ↔ AI Act Relationship

- AI training data may fall under Data Act data access obligations
- Connected product data used for AI must comply with both regulations
- Cloud switching rights facilitate AI vendor changes
- Data portability enables multi-vendor AI strategies

### What This Means for Your AI Procurement

**Before selecting an AI vendor, verify**:
1. Data export capabilities in standard, machine-readable formats
2. Switching terms — no excessive fees or lock-in after Sept 2025 (zero fees from Jan 2027)
3. API access to all your data (not just dashboards or reports)
4. Contract terms comply with Chapter III fairness requirements
5. International data access safeguards for EU-stored data
6. Interoperability with other cloud/AI services`,
    badgeType: "EU",
    criteriaCount: 34,
    effectiveDate: "Sep 2025",
    issuingAuthority: "European Parliament & Council of the EU",
    enforcementType:
      "Legal — Directly applicable EU Regulation (no national transposition needed)",
    maxPenalty:
      "Penalties set by member states — must be effective, proportionate, and dissuasive. Cloud switching charges must reach zero by January 2027.",
    applicableRegions: "All EU/EEA member states (directly applicable)",
    purpose:
      "Establish harmonized rules on fair access to and use of data, including cloud switching rights, data portability, and protection against unfair contract terms in data-related services.",
    officialUrl:
      "https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:32023R2854",
    industrySlugs: [
      "financial-services",
      "manufacturing",
      "telecommunications",
      "healthcare",
      "energy-utilities",
    ],
  },

  // ── Digital Services Act ──────────────────────────────────
  {
    slug: "dsa",
    name: "Digital Services Act (DSA)",
    description:
      "The Digital Services Act (Regulation 2022/2065) is the EU's landmark regulation governing digital platforms and online intermediaries. It introduces algorithmic transparency obligations, content moderation requirements, and systemic risk assessments for very large online platforms (VLOPs). Directly relevant to AI platforms that serve EU users or deploy recommender systems.",
    content: `## Digital Services Act — Platform Obligations & Algorithmic Transparency

### Overview

The Digital Services Act (Regulation (EU) 2022/2065) establishes comprehensive rules for digital services operating in the EU. It creates a tiered system of obligations based on the type and size of the digital service, with the most stringent rules applying to Very Large Online Platforms (VLOPs) and Very Large Online Search Engines (VLOSEs).

**Key purpose**: Create a safer digital space, protect fundamental rights online, ensure platform accountability, and establish algorithmic transparency requirements.

### Who Must Comply

The DSA applies to all digital services that serve EU users, regardless of where the provider is established. Four tiers with increasing obligations:

1. **Intermediary services** (all providers): Basic transparency, cooperation with authorities
2. **Hosting services** (incl. cloud): Notice-and-action mechanisms, transparency reporting
3. **Online platforms** (with content): Additional obligations around advertising, recommender systems, content moderation
4. **Very Large Online Platforms (VLOPs) / Very Large Online Search Engines (VLOSEs)**: 45M+ monthly active EU users — systemic risk assessment, independent audits, algorithmic transparency, crisis response

### VLOPs and VLOSEs (as of 2026)

The European Commission has designated the following as VLOPs/VLOSEs (relevant to AI):
- **Google** (Search, Maps, Play, Shopping, YouTube)
- **Microsoft** (Bing, LinkedIn)
- **Meta** (Facebook, Instagram)
- **Apple** (App Store)
- **Amazon** (Marketplace)
- **TikTok** (ByteDance)
- **X** (formerly Twitter)
- **Booking.com**
- **Wikipedia**
- **Zalando** (later successfully challenged — removed from list by EU Court, Feb 2025)
- **AliExpress** (Alibaba)
- **Pinterest**
- **Snapchat**

### Key Obligations for AI

**Algorithmic Transparency (Article 27)**

Online platforms using recommender systems must:
- Explain the main parameters used in their recommender systems in plain language
- Provide at least one option NOT based on user profiling
- Disclose when content is recommended by an algorithm vs. shown chronologically

For AI procurement: If your enterprise deploys AI-powered recommendation or personalization tools serving EU users, you may need to provide algorithmic transparency to end users.

**Risk Assessment (Articles 34-35)**

VLOPs and VLOSEs must conduct systemic risk assessments at least annually, covering:
- Dissemination of illegal content
- Negative effects on fundamental rights (privacy, non-discrimination, freedom of expression)
- Negative effects on civic discourse, electoral processes, and public security
- Negative effects related to gender-based violence and child protection
- Actual or foreseeable negative effects on public health and minors

**AI-generated content and deepfakes (Article 35a)**

VLOPs must identify and label AI-generated or manipulated content (deepfakes). This includes:
- Clear, prominent labeling that content is AI-generated
- Technical means for users to indicate AI-generated content
- Interoperable metadata standards (e.g., C2PA Content Credentials)

**Advertising Transparency (Articles 26, 39)**

All online platforms:
- Must clearly label advertisements as such
- Must disclose the person paying for the ad and targeting parameters
- Must not use sensitive personal data for ad targeting (health, religion, political opinions, sexual orientation)

VLOPs additionally:
- Must maintain publicly accessible advertisement repositories
- Must provide researchers access to ad targeting data

**Content Moderation and Due Diligence (Articles 14-16)**

Hosting services (including cloud/AI platforms):
- Must establish notice-and-action mechanisms for illegal content
- Must provide clear terms of service explaining content moderation policies
- Must report suspected criminal activity to law enforcement

### Enforcement Timeline

- **16 November 2022**: DSA entered into force
- **17 February 2024**: Full application for VLOPs and VLOSEs
- **17 February 2024**: Full application for all digital service providers
- **Ongoing**: Commission enforcement actions and investigations

### Enforcement Actions (2025-2026)

The European Commission has opened formal proceedings against:
- **X (Twitter)**: Risk management, content moderation, advertising transparency, data access for researchers (Dec 2023 — preliminary findings of non-compliance issued Jul 2024)
- **TikTok**: Protection of minors, advertising transparency, data access (Feb 2024)
- **AliExpress**: Product safety, content moderation (Mar 2024)
- **Meta**: Deceptive design patterns ("pay or consent" model), election-related content moderation (Apr-May 2024)
- **Temu**: Sale of illegal products, addictive design features, recommender systems (Oct 2024)
- **Shein**: Product safety, recommender system transparency (2025)

### Penalties

- **VLOPs/VLOSEs**: Up to 6% of global annual turnover
- **Other providers**: Up to 6% of annual income/turnover
- **Repeated infringements**: Can lead to temporary service suspension in the EU
- **Misleading information**: Up to 1% of global annual turnover

### DSA ↔ AI Act Interaction

- The AI Act's transparency requirements for AI-generated content complement the DSA's deepfake labeling obligations
- VLOPs deploying high-risk AI systems must comply with both DSA systemic risk assessments and AI Act requirements
- Recommender systems may be classified as limited-risk under the AI Act (transparency obligations)
- Both regulations require human oversight of automated decision-making

### What This Means for Your AI Procurement

**If your enterprise provides digital services to EU users**:
1. Assess whether your AI-powered platform qualifies as an online platform or VLOP
2. Ensure recommender systems are transparent with non-profiling alternatives
3. Implement AI-generated content labeling (especially for generative AI outputs)
4. Review ad targeting — no sensitive data categories
5. Establish notice-and-action mechanisms for AI-related illegal content
6. If VLOP: conduct systemic risk assessments covering AI-related risks`,
    badgeType: "EU",
    criteriaCount: 43,
    effectiveDate: "Feb 2024",
    issuingAuthority: "European Parliament & Council of the EU",
    enforcementType:
      "Legal — Directly applicable EU Regulation. Commission enforces for VLOPs; national Digital Services Coordinators for others.",
    maxPenalty:
      "Up to 6% of global annual turnover for VLOPs/VLOSEs. Repeated infringements can lead to temporary service suspension in the EU.",
    applicableRegions:
      "All EU/EEA member states (directly applicable). Also applies to non-EU providers serving EU users.",
    purpose:
      "Create a safer digital space by establishing platform accountability, algorithmic transparency, content moderation requirements, and systemic risk management for digital services operating in the EU.",
    officialUrl:
      "https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:32022R2065",
    industrySlugs: [
      "telecommunications",
      "financial-services",
      "public-sector",
    ],
  },

  // ── Digital Markets Act ───────────────────────────────────
  {
    slug: "dma",
    name: "Digital Markets Act (DMA)",
    description:
      "The Digital Markets Act (Regulation 2022/1925) targets large digital platforms designated as 'gatekeepers' — companies that control key platform services used by millions of EU users. It imposes obligations around data portability, interoperability, fair access, and prohibition of self-preferencing. Impacts AI procurement by ensuring enterprises can access their data and switch between gatekeeper platforms.",
    content: `## Digital Markets Act — Gatekeeper Obligations & Fair Competition

### Overview

The Digital Markets Act (Regulation (EU) 2022/1925) regulates large digital platforms designated as "gatekeepers" — companies that control core platform services and act as important gateways between businesses and consumers. The DMA aims to ensure fair and contestable digital markets by preventing gatekeepers from abusing their market position.

**Key purpose**: Level the playing field for businesses dependent on gatekeeper platforms, ensure data portability, enable interoperability, and prevent anti-competitive practices.

### Who Are the Gatekeepers?

As of 2026, the European Commission has designated the following companies as gatekeepers:

| Company | Core Platform Services |
|---------|----------------------|
| **Alphabet/Google** | Google Search, Google Maps, Google Play, Google Shopping, YouTube, Google Android, Google Chrome, Google Ads |
| **Amazon** | Amazon Marketplace, Amazon Ads |
| **Apple** | iOS, App Store, Safari, iMessage |
| **ByteDance** | TikTok, TikTok Ads |
| **Meta** | Facebook, Instagram, WhatsApp, Messenger, Meta Marketplace, Meta Ads |
| **Microsoft** | Windows, LinkedIn, Microsoft Ads |
| **Booking.com** | Booking.com (designated 2024) |

### Gatekeeper Designation Criteria

A company is presumed to be a gatekeeper if it meets ALL of the following (Article 3):
- **€7.5B+ annual EEA turnover** (or €75B+ market cap) in the last 3 financial years
- **45M+ monthly active end users** in the EU
- **10,000+ yearly active business users** in the EU
- The company provides a **core platform service** in at least 3 EU member states

### Key Obligations Relevant to AI Procurement

**1. Data Portability (Article 6(9))**

Gatekeepers must provide business users and end users with effective portability of data generated through their activity. This means:
- You can extract your data from Google Workspace, Microsoft 365, etc.
- Data must be provided in a usable, machine-readable format
- Continuous, real-time data portability tools must be available
- Cannot charge excessive fees for data export

For AI procurement: If you're using AI tools built on gatekeeper platforms, you have the right to move your data to competing AI services.

**2. Interoperability (Article 7)**

Messaging services of gatekeepers must be interoperable with third-party messaging services:
- Text and image messages (from March 2024)
- Group messaging and voice/video calls (from March 2027)
- End-to-end encryption must be maintained

For AI procurement: AI communication tools built on gatekeeper messaging platforms (e.g., WhatsApp, iMessage) must enable interoperability.

**3. No Self-Preferencing (Article 6(5))**

Gatekeepers cannot treat their own products or services more favorably than third-party offerings in ranking or display. This applies to:
- Search results (Google cannot preference Google products in search)
- App store rankings (Apple cannot preference Apple apps)
- Marketplace listings (Amazon cannot preference Amazon brands)

For AI procurement: AI tools recommended or promoted within gatekeeper ecosystems must compete on merit, not preferential treatment.

**4. No Data Combination (Article 5(2))**

Gatekeepers cannot combine personal data from different core platform services without explicit user consent (GDPR Article 6(1)(a) standard). This means:
- Google cannot combine YouTube data with Search data without consent
- Meta cannot combine WhatsApp data with Facebook data without consent

For AI procurement: AI models trained on combined gatekeeper data may face compliance challenges.

**5. Fair Access to Platform Services (Article 6(12))**

Gatekeepers must apply fair, reasonable, and non-discriminatory (FRAND) terms for access to app stores and other core platform services. Third-party AI apps must receive equitable treatment.

### Enforcement Actions (2025-2026)

The European Commission has been actively enforcing the DMA:

- **Apple**: Preliminary findings of non-compliance on App Store steering rules (anti-steering provisions preventing developers from directing users to alternative payment options). Multiple proceedings ongoing.
- **Google**: Investigation into search self-preferencing, Google Play terms, and choice screen compliance.
- **Meta**: Investigation into "pay or consent" model (charging for ad-free Facebook/Instagram). Preliminary finding of non-compliance (Jul 2024).
- **Amazon**: Investigation into self-preferencing in Marketplace (Buy Box, Prime). Case closed after commitments (2025).
- **Microsoft**: Edge/Bing default settings on Windows. Investigation ongoing.
- **Booking.com**: Designated as gatekeeper in 2024. Compliance assessment underway.

### Penalties

- **Non-compliance**: Up to **10% of worldwide annual turnover**
- **Repeated infringements**: Up to **20% of worldwide annual turnover**
- **Systematic non-compliance**: Behavioral or structural remedies, including forced divestiture
- **Incorrect information**: Up to 1% of worldwide annual turnover
- **Failure to notify concentration**: Up to 1% of worldwide annual turnover

### DMA ↔ AI Act Interaction

- Gatekeepers deploying AI systems must comply with both DMA obligations and AI Act requirements
- Data portability obligations under DMA facilitate AI vendor switching (complementary to Data Act)
- Self-preferencing prohibition applies to AI services within gatekeeper ecosystems
- AI-driven ranking and recommendation systems on gatekeeper platforms face dual scrutiny

### DMA ↔ Data Act Relationship

Both regulations promote data portability and switching:
- Data Act: horizontal rules for all cloud/data processing services
- DMA: specific rules for designated gatekeepers only
- DMA goes further with real-time portability and interoperability requirements
- Together, they create a strong framework against vendor lock-in

### What This Means for Your AI Procurement

**If you procure AI tools from or built on gatekeeper platforms**:
1. You have strong data portability rights — exercise them when evaluating alternatives
2. Gatekeeper platforms cannot lock you in through technical or contractual barriers
3. AI tools from non-gatekeepers must receive equal treatment in gatekeeper ecosystems
4. Combination of your data across gatekeeper services requires your explicit consent
5. Third-party AI apps on gatekeeper platforms benefit from FRAND access terms
6. Use DMA rights as negotiation leverage in procurement discussions`,
    badgeType: "EU",
    criteriaCount: 22,
    effectiveDate: "Mar 2024",
    issuingAuthority: "European Parliament & Council of the EU",
    enforcementType:
      "Legal — Directly applicable EU Regulation. Enforced exclusively by the European Commission (centralized enforcement).",
    maxPenalty:
      "Up to 10% of worldwide annual turnover (20% for repeated infringements). Structural remedies including forced divestiture for systematic non-compliance.",
    applicableRegions:
      "All EU/EEA member states. Applies to gatekeepers regardless of establishment. Enforced centrally by the European Commission.",
    purpose:
      "Ensure fair and contestable digital markets by regulating large 'gatekeeper' platforms, preventing anti-competitive practices, and enabling data portability, interoperability, and fair access for businesses and consumers.",
    officialUrl:
      "https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:32022R1925",
    industrySlugs: ["telecommunications", "financial-services"],
  },
];

// ─── Policy Statements ─────────────────────────────────────

const policyStatements = [
  // Data Act statements
  {
    frameworkSlug: "data-act",
    sectionTitle: "Data Access and Sharing",
    statements: [
      {
        statement:
          "Users of connected products have the right to access data generated by those products, and to share that data with third parties of their choice, in a commonly used and machine-readable format.",
        commentary:
          "Articles 3-5 establish a fundamental right to data generated by connected products. For AI procurement: if you deploy IoT devices or connected industrial equipment with AI analytics, the data belongs to you — not the device manufacturer or AI service provider. You can share it with any third-party AI provider.",
        sortOrder: 1,
      },
      {
        statement:
          "Data holders shall make data available to data recipients under fair, reasonable, and non-discriminatory terms, and any compensation shall not exceed reasonable margins over the cost of making the data available.",
        commentary:
          "Articles 8-9 prevent data gatekeeping. AI vendors processing your connected product data cannot charge excessive fees for data access. This is critical when switching AI analytics providers — your current vendor cannot exploit your data dependency.",
        sortOrder: 2,
      },
    ],
  },
  {
    frameworkSlug: "data-act",
    sectionTitle: "Cloud Switching and Portability",
    statements: [
      {
        statement:
          "Cloud and AI service providers must enable customers to switch to alternative providers within 30 calendar days, with switching charges reduced to zero from 12 January 2027.",
        commentary:
          "Articles 23-31 are transformative for AI procurement. After January 2027, your cloud/AI provider cannot charge switching fees. The 30-day switching window (extendable to 60) means you can credibly threaten to switch — use this as procurement leverage. Functional equivalence requirements mean the receiving provider should achieve substantially similar results.",
        sortOrder: 1,
      },
      {
        statement:
          "Cloud and AI service providers shall not impose contractual, commercial, technical, or organizational barriers to switching, and must provide open interfaces and data export in standard formats.",
        commentary:
          "Article 25 prohibits all forms of vendor lock-in. This includes: proprietary data formats, API restrictions, contractual penalties, and technical obstacles to data migration. If your AI vendor makes switching difficult, they're likely in violation of the Data Act from September 2025.",
        sortOrder: 2,
      },
    ],
  },
  {
    frameworkSlug: "data-act",
    sectionTitle: "International Data Safeguards",
    statements: [
      {
        statement:
          "Cloud and data processing service providers shall take reasonable technical, legal, and organizational measures to prevent international transfer of, or government access to, non-personal data held in the EU where such transfer or access would conflict with EU law.",
        commentary:
          "Articles 32-34 reinforce EU data sovereignty. This complements GDPR international transfer rules by extending protection to non-personal data. For AI procurement: your vendor cannot comply with non-EU government data requests (e.g., US CLOUD Act) that conflict with EU law. Verify your AI vendor's international data access policies.",
        sortOrder: 1,
      },
    ],
  },

  // DSA statements
  {
    frameworkSlug: "dsa",
    sectionTitle: "Algorithmic Transparency",
    statements: [
      {
        statement:
          "Online platforms using recommender systems shall set out in their terms and conditions the main parameters used in their recommender systems, and provide users with an easily accessible option to modify or influence those parameters, including at least one option not based on profiling.",
        commentary:
          "Article 27 is the DSA's most AI-relevant provision. If your enterprise deploys AI recommendation or personalization systems serving EU users, you must explain the algorithm's main parameters in plain language and offer a non-profiling alternative. This applies to product recommendations, content feeds, search results, and personalized experiences.",
        sortOrder: 1,
      },
      {
        statement:
          "Very large online platforms shall identify, analyze, and assess systemic risks stemming from the design, functioning, and use of their services, including algorithmic systems, at least once a year.",
        commentary:
          "Articles 34-35 require VLOPs to conduct annual systemic risk assessments covering their AI systems. Risks include: dissemination of illegal content, negative effects on fundamental rights, impacts on civic discourse and elections, and effects on public health and minors. This is essentially a mandatory AI impact assessment for large platforms.",
        sortOrder: 2,
      },
    ],
  },
  {
    frameworkSlug: "dsa",
    sectionTitle: "AI-Generated Content",
    statements: [
      {
        statement:
          "Very large online platforms shall label AI-generated or manipulated content (deepfakes) in a clear, prominent manner, and provide technical means for users and content creators to indicate AI-generated content.",
        commentary:
          "Article 35a introduces mandatory AI content labeling. This complements the AI Act's transparency obligations for AI-generated content. For enterprises using generative AI: any AI-generated content published on VLOP platforms must be clearly labeled. Adopt Content Credentials (C2PA) standards to comply proactively.",
        sortOrder: 1,
      },
    ],
  },
  {
    frameworkSlug: "dsa",
    sectionTitle: "Advertising and Targeting",
    statements: [
      {
        statement:
          "Online platforms shall not present advertisements based on profiling using sensitive personal data categories including health, religion, political opinions, racial or ethnic origin, or sexual orientation.",
        commentary:
          "Article 26(3) directly impacts AI-powered advertising and marketing tools. If your enterprise uses AI for ad targeting, ensure the system cannot infer or use sensitive categories — even indirectly through proxy variables. This is a strict prohibition, not a consent-based exception.",
        sortOrder: 1,
      },
    ],
  },

  // DMA statements
  {
    frameworkSlug: "dma",
    sectionTitle: "Data Portability",
    statements: [
      {
        statement:
          "Gatekeepers shall provide business users and end users with effective portability of data generated through their activity on the gatekeeper's core platform services, including continuous and real-time access through appropriate technical measures.",
        commentary:
          "Article 6(9) gives you strong data extraction rights from gatekeeper platforms. If you're using Google Workspace, Microsoft 365, Amazon services, or Apple's ecosystem, you can demand continuous, real-time data portability. This enables multi-cloud and multi-vendor AI strategies without data lock-in.",
        sortOrder: 1,
      },
      {
        statement:
          "Gatekeepers shall not use, in competition with business users, any data that is not publicly available and is generated through or provided in the context of the activities of those business users on the gatekeeper's platform.",
        commentary:
          "Article 6(2) prevents gatekeepers from using your business data to compete against you. If you use Amazon Marketplace, Apple App Store, or Google Play, the gatekeeper cannot use your sales data, usage patterns, or business intelligence to develop competing products or train AI models that compete with your offerings.",
        sortOrder: 2,
      },
    ],
  },
  {
    frameworkSlug: "dma",
    sectionTitle: "Interoperability and Fair Access",
    statements: [
      {
        statement:
          "Gatekeepers shall allow and technically enable the installation and effective use of third-party software applications or software application stores, and shall not use disproportionate measures to ensure that third-party apps function as well as the gatekeeper's own apps.",
        commentary:
          "Articles 6(4) and 6(7) ensure third-party AI applications can compete fairly on gatekeeper platforms. This means: alternative AI assistants on iOS/Android must be permitted, third-party AI apps in gatekeeper app stores must receive equitable treatment, and side-loading must be technically enabled (particularly relevant for Apple's iOS).",
        sortOrder: 1,
      },
    ],
  },
  {
    frameworkSlug: "dma",
    sectionTitle: "Self-Preferencing Prohibition",
    statements: [
      {
        statement:
          "Gatekeepers shall not treat more favorably, in ranking and related indexing and crawling, services and products offered by the gatekeeper itself compared to similar services or products offered by third parties.",
        commentary:
          "Article 6(5) directly impacts AI tool discovery and adoption. Google cannot preference its own AI tools (Gemini, Bard) in search results. Amazon cannot preference its own AI services (Bedrock, SageMaker) in AWS Marketplace. Apple cannot preference its own AI (Apple Intelligence) in the App Store. This ensures a level playing field for AI vendor selection.",
        sortOrder: 1,
      },
    ],
  },
];

// ─── Seed Runner ───────────────────────────────────────────

async function main() {
  console.log("Seeding new regulatory frameworks (Batch 3)...\n");

  // Upsert frameworks
  for (const fw of frameworks) {
    const { industrySlugs, ...data } = fw;

    const framework = await prisma.regulatoryFramework.upsert({
      where: { slug: data.slug },
      update: data,
      create: { ...data, published: true },
    });

    // Connect industries
    if (industrySlugs?.length) {
      const industries = await prisma.industry.findMany({
        where: { slug: { in: industrySlugs } },
      });
      await prisma.regulatoryFramework.update({
        where: { id: framework.id },
        data: {
          industries: {
            set: industries.map((i) => ({ id: i.id })),
          },
        },
      });
    }

    console.log(`  ✓ Framework: ${data.name}`);
  }

  // Upsert sections and policy statements
  for (const item of policyStatements) {
    const framework = await prisma.regulatoryFramework.findUnique({
      where: { slug: item.frameworkSlug },
    });
    if (!framework) {
      console.warn(`  ✗ Framework not found: ${item.frameworkSlug}`);
      continue;
    }

    // Find or create section
    let section = await prisma.frameworkSection.findFirst({
      where: {
        frameworkId: framework.id,
        title: item.sectionTitle,
      },
    });

    if (!section) {
      const maxOrder = await prisma.frameworkSection.aggregate({
        where: { frameworkId: framework.id },
        _max: { sortOrder: true },
      });
      section = await prisma.frameworkSection.create({
        data: {
          title: item.sectionTitle,
          frameworkId: framework.id,
          sortOrder: (maxOrder._max.sortOrder || 0) + 1,
        },
      });
    }

    // Upsert statements
    for (const stmt of item.statements) {
      const existing = await prisma.policyStatement.findFirst({
        where: {
          sectionId: section.id,
          statement: stmt.statement,
        },
      });

      if (!existing) {
        await prisma.policyStatement.create({
          data: {
            sectionId: section.id,
            statement: stmt.statement,
            commentary: stmt.commentary,
            sortOrder: stmt.sortOrder,
          },
        });
      }
    }

    console.log(
      `    ✓ Section: ${item.sectionTitle} (${item.statements.length} statements)`
    );
  }

  console.log(
    `\nDone — seeded ${frameworks.length} frameworks with policy statements.`
  );
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
